# Workflow for testing spoon code quality.
#
# Note that actions are specified by commit hash. This is to avoid the security
# risk of someone injecting malicious code into a release and then simply
# changing a tag.

name: Qodana
on:
  pull_request:
    branches:
      - master
jobs:
    code-quality:
      runs-on: ubuntu-latest
      name: code-quality qodana
      steps:
        - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
          with:
            fetch-depth: 0
        - name: 'Qodana Scan'
          uses: JetBrains/qodana-action@32840fdb87f8dd110e0a6b09323c7142b667b25d # v2024.1.5
          with:
            args: --source-directory,./src/main/java , --fail-threshold, 0
            post-pr-comment: "false"
        - uses: github/codeql-action/upload-sarif@b7cec7526559c32f1616476ff32d17ba4c59b2d6 # v3
          with:
            sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
    code-quality-spoon-javadoc:
      runs-on: ubuntu-latest
      name: code-quality spoon-javadoc qodana
      steps:
        - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
          with:
            fetch-depth: 0
        - name: 'Qodana Scan (spoon-javadoc)'
          uses: JetBrains/qodana-action@32840fdb87f8dd110e0a6b09323c7142b667b25d # v2024.1.5
          with:
            args: --source-directory,./spoon-javadoc/src/main/java , --fail-threshold, 0
            post-pr-comment: "false"
        - uses: github/codeql-action/upload-sarif@b7cec7526559c32f1616476ff32d17ba4c59b2d6 # v3
          with:
            sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
    code-quality-spoon-control-flow:
      runs-on: ubuntu-latest
      name: code-quality spoon-controlflow qodana
      steps:
        - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
          with:
            fetch-depth: 0
        - name: 'Qodana Scan (spoon-control-flow)'
          uses: JetBrains/qodana-action@32840fdb87f8dd110e0a6b09323c7142b667b25d # v2024.1.5
          with:
            args: --source-directory,./spoon-control-flow/src/main/java , --fail-threshold, 0
            post-pr-comment: "false"
        - uses: github/codeql-action/upload-sarif@b7cec7526559c32f1616476ff32d17ba4c59b2d6 # v3
          with:
            sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
